# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Evans < Formula
  desc "Evans: more expressive universal gRPC client"
  homepage "https://evans.syfm.me"
  version "0.10.10"

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.10/evans_darwin_amd64.tar.gz"
      sha256 "6eb8ad10b3e7f320939aeeb04bbddfc79d3c1329b85441d7d7f9161e5afe20d3"

      def install
        bin.install "evans"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.10/evans_linux_arm.tar.gz"
      sha256 "70346b95bb040eef6abbec02bb3666bbb95d082dd3492766702f9cc2b791be1e"

      def install
        bin.install "evans"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.10/evans_linux_arm64.tar.gz"
      sha256 "2bd9a87963276694d2c4c3685e581293a5e01896d36e89ce417f95fdae674edd"

      def install
        bin.install "evans"
      end
    end
    if Hardware::CPU.intel?
      url "http://github.com/ktr0731/evans/releases/download/v0.10.10/evans_linux_amd64.tar.gz"
      sha256 "c0ab07b5ee56117b5a4ead96e1d1ea670f0e4062a7b80121ab222837a86720b3"

      def install
        bin.install "evans"
      end
    end
  end
end
